---
title: "brnum_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## BrNum data

```{r}
library('readxl')

```

```{r}
brdata = as.data.frame(read_excel("BrNum_LIBDIntranet_031221.n2511.xlsx"))
colnames(brdata)=tolower(colnames(brdata))
colnames(brdata)[colnames(brdata) == "primarydx"] <- "dx"
colnames(brdata)[colnames(brdata) ==  "agedeath"] <- "age"
colnames(brdata)[colnames(brdata) ==  "manner of death"] <- "mod"
brdata$dx[brdata$dx=="BPNOS"] <- "BpNOS"
brdata$dx[brdata$dx=="Alzheimer"] <- "AD"
brdata$brint <- as.integer(gsub("^[^[:digit:]]+", '', brdata$brnum))
brdata$dx_id <- as.integer(0)
## -- shuffle!
set.seed(42)
brdata <- brdata[sample(nrow(brdata)),]

```

```{r}
#library('dplyr')
library('RPostgreSQL')

dbp <- read.delim(".pgpass", sep=":", header=TRUE)
pg_db <- "rse"
pg_user <- subset(dbp, database=="rse")[[1,4]]
pg_pass <- subset(dbp, database=="rse")[[1,5]]

pg <- dbDriver("PostgreSQL")

con <- dbConnect(pg, dbname=pg_db, user=pg_user, password=pg_pass, host="gdebsrv")
#dbListTables(con)
r <- dbGetQuery(con, "select count(*) from subjects")
message("Subjects count: ",r$count)
```

## Load Br data in a temporary table
```{r}
r <- dbGetQuery(con, "drop table if exists subj_tmp")
dbWriteTable(con, name="subj_tmp", value=brdata, append=FALSE, row.names=FALSE, temporary=TRUE)
r <- dbGetQuery(con, "CREATE UNIQUE INDEX idx_subjtmp_n ON subj_tmp (brnum)")
r <- dbGetQuery(con, "CREATE UNIQUE INDEX idx_subjtmp_i ON subj_tmp (brint)")
r <- dbGetQuery(con, "select count(*) from subj_tmp")
message(r$count, " rows loaded in subj_tmp")
```
## Validation and possible updates
## fill subj_tmp.dx_id first
```{r}
r <- dbGetQuery(con, "UPDATE subj_tmp t SET dx_id=d.id FROM dx d 
 WHERE lower(t.dx) = lower(d.dx) OR d.name ILIKE t.dx || '%'")
r <- dbGetQuery(con, "SELECT brnum, dx, age, sex, race from subj_tmp WHERE dx_id=0")
if (nrow(r)>0) {
  message("WARNING: ", nrow(r), " entries have unrecognized diagnosis!")
  head(r)
  stop("Update the dx table if needed or correct spelling of these entries")
  
}
```


```{r}
rdsex <- dbGetQuery(con, "select s.brnum, s.sex, t.sex from subjects s, subj_tmp t where s.brint=t.brint and s.sex!=CAST(t.sex as subjsex)")
if (nrow(rdsex)>0) {
  message("WARNING: ", nrow(rdsex), " entries have different sex!")
  stop("Problems: check your data!")
}

rdrace <- dbGetQuery(con, "select s.brnum, s.race, t.race from subjects s, subj_tmp t where s.brnum=t.brnum and s.race!=CAST(t.race as subjrace)")
if (nrow(rdrace)>0) {
  message("WARNING: ", nrow(rdrace), " entries have different race! Updating..")
  #stop("Problems: check your data!")
  uq <- dbGetQuery(con, "update subjects s set race=CAST(t.race as subjrace) FROM subj_tmp t
                    where t.brint=s.brint and s.race!=CAST(t.race AS subjrace)")
}


rdage <- dbGetQuery(con, "SELECT s.brnum, s.age, t.age FROM subjects s, subj_tmp t 
                    WHERE s.brint=t.brint AND s.age != CAST(t.age as NUMERIC(5,2))")
if (nrow(rdage)>0) {
  message("WARNING: ", nrow(rdage), " entries have different age, updating..")
  head(rdage)
  r <- dbGetQuery(con, "UPDATE subjects s SET age=CAST(t.age as NUMERIC(5,2)) FROM subj_tmp t
                  WHERE s.brint=t.brint AND s.age!=CAST(t.age as NUMERIC(5,2))")
}


```

##Update NULL PMI and mod and add missing entries
```{r}
r <- dbGetQuery(con, "update subjects s set pmi=CAST(t.pmi as NUMERIC(5,1)) FROM subj_tmp t
                    where t.brint=s.brint and s.pmi is NULL")
r <- dbGetQuery(con, "update subjects s set mod=t.mod FROM subj_tmp t
                    where t.brint=s.brint and s.mod is NULL AND t.mod is not NULL")
r <- dbGetQuery(con, "INSERT INTO subjects (brnum, brint, age, sex, race, dx_id, mod, pmi)
                SELECT t.brnum, t.brint, CAST(t.age as NUMERIC(5,2)), CAST(t.sex as subjsex), 
 CAST(t.race as subjrace), t.dx_id, t.mod, t.pmi from subj_tmp t where 
   NOT EXISTS( SELECT * from subjects s where s.brint = t.brint)")
```

```{r}
r <- dbGetQuery(con, "select count(*) from subjects")
message("Subjects count: ",r$count)
## - show likely dropped BrNums that Amy no longer provides/supports
sq <- "with x as (select s.id, brnum, brint, dx from subjects s, dx 
    where s.dx_id=dx.id AND NOT EXISTS (select * from subj_tmp t where s.brint=t.brint))
 SELECT 'P'||trim(to_char(x.id, '00000')) as p_id, brnum, brint, dx, string_agg(s.name,',') as samples 
 from x, samples s where s.subj_id=x.id GROUP BY x.id, brnum, brint, dx"
brmiss <- dbGetQuery(con,sq)
if (nrow(brmiss)>0) {
  message(nrow(brmiss), " entries were not provided by LIMS")
  head(brmiss, n=20)
}
```
```{r}
qry <- "SELECT 'P'||trim(to_char(s.id, '00000')) as p_id, brnum, brint, dx, sex, race, age, pmi, mod, dropped 
 FROM subjects s, dx d where d.id=s.dx_id ORDER BY 1";
subj <- dbGetQuery(con, qry)
write.table(subj, file="subjects_data.tab", row.names = F, sep = "\t", quote=F)

qry <- "SELECT s.name, 'P'||trim(to_char(p.id, '00000')) as p_id, brnum, brint, dx, sex, race, age, pmi 
 FROM subjects p, dx d, samples s WHERE s.subj_id=p.id AND d.id=p.dx_id ORDER BY 1"
samp <- dbGetQuery(con, qry)
write.table(samp, file="samples_phenodata.tab", row.names = F, sep = "\t", quote=F)

```




