---
title: "rse_gene_all"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup libraries

```{r}
library("SummarizedExperiment")
library("dplyr")
```

## load latest rse_gene object

```{r}
#load("data/RNAseq_Collection_postQC_n5536_11dataset_2021-01-07_geneRSE.Rdata")
load("data/RNAseq_Collection_postQC_n5536_11dataset_2021-01_geneRSE.Rdata")
g_cd <- as.data.frame(colData(rse_gene))
g_rd <- as.data.frame(rowData(rse_gene))
g_a <- assay(rse_gene)
```


### Connect to database

```{r}
library('RPostgreSQL')

dbp <- read.delim(".pgpass", sep=":", header=TRUE)
pg_db <- "rse"
pg_user <- subset(dbp, database=="rse")[[1,4]]
pg_pass <- subset(dbp, database=="rse")[[1,5]]

pg <- dbDriver("PostgreSQL")

con <- dbConnect(pg, dbname=pg_db, user=pg_user, password=pg_pass, host="gdebsrv")
#show tables
dbListTables(con)
```
##Regions table
Only execute this once for loading initial data
```{r}
regtable <- read.table("brain_regions.csv", header=T, sep=',')
dbWriteTable(con, name="regs_tmp", value=regtable, append=FALSE, row.names=FALSE, temporary=TRUE)
qry <- "INSERT into regions (name, fullname, alts)
SELECT t.name, t.fullname, string_to_array(lower(t.alts), '|')
  FROM regs_tmp t WHERE not exists (SELECT * from regions r where r.name = t.name)"
dbGetQuery(con, qry)
dbGetQuery(con, "drop table regs_tmp")
```


### Loading the `subjects` table from rse_gene:

```{r}
#select columns of interest
sd <- g_cd[ c("BrNum", "Age", "Sex", "Race", "Dx") ]
#convert column names to lowercase
colnames(sd) <- tolower(colnames(sd))
#remove row names
rownames(sd) <- NULL
## remove duplicate BrNum entries, keeping only the last one in each group
sdf <- sd[!duplicated(sd$brnum, fromLast=T),]
## populate the subjects table by only looking at 
#---load in a temporary table so only new BrNums are appended

dbWriteTable(con, name="subj_tmp", value=sdf, append=FALSE, row.names=FALSE, temporary=TRUE)
r <- dbGetQuery(con, "CREATE UNIQUE INDEX idx_subjtmp_n ON subj_tmp (BrNum)")

qry <- "INSERT into subjects (brnum, age, sex, race, dx)
 SELECT DISTINCT t.brnum, cast(t.age as real), cast(t.sex as subjsex),
            cast(t.race as subjrace), cast(t.dx as subjdx) from subj_tmp t 
            WHERE NOT EXISTS (SELECT * from subjects s where s.brnum = t.brnum)"
r <- dbGetQuery(con, qry)

r <- dbGetQuery(con, "drop table subj_tmp")
r <- dbGetQuery(con, "select count(*) from subjects")
cat("Subjects loaded: ",r$count,"\n")
```

### Loading the datasets table
```{r}
## -- update datasets table
dsfreq <- as.data.frame(table(g_cd$Dataset, dnn=c("name")))
colnames(dsfreq) <- tolower(colnames(dsfreq))
dbWriteTable(con, name="dsets_tmp", value=dsfreq, append=FALSE,
             row.names=FALSE, temporary=TRUE)
qry <- "INSERT into datasets (name)
  SELECT t.name from dsets_tmp t where 
    NOT EXISTS( SELECT * from datasets d where d.name = t.name )"
r <- dbGetQuery(con, qry)
v <- dbGetQuery(con, "drop table dsets_tmp")
cat("Datasets added: ",nrow(r),"\n")
```

```{r}
## load the datasets and subjects in dataframes to get the ids
ds <- dbGetQuery(con, 'select * from datasets')
subj <- dbGetQuery(con, 'select * from subjects')
regs <- dbGetQuery(con, 'select * from regions')

## create a smp dataframe to load data from
smp <- g_cd[ c("BrNum", "Dataset", "SAMPLE_ID", "RNum", "RIN", "Region", 
    "numReads", "numMapped","numUnmapped", "mitoMapped", "totalMapped",
    "overallMapRate", "concordMapRate", "mitoRate", "rRNA_rate", "totalAssignedGene", "bamFile") ]
colnames(smp) <- tolower(colnames(smp))
## simplify sample_id so it has only the first lane suffix
smp$sample_id <- sapply(smp$sample_id, function(x) {
  mp <- regexpr(';',x, fixed=TRUE)
  if (mp[[1]]==-1) return(x)
  return(substr(x,1,m[[1]]-1))
})

nd <- sum( duplicated(smp$sample_id) )
if (nd>0) 
  stop("Error: duplicates found in sample_id after semicolon truncation")
#smp$bamfile <- sapply(smp[,"bamFile"], paste, collapse=';')
## simplify bamfile lists so the path is only kept once
smp$bamfile <- sapply(smp$bamfile, function(x) {
  if (length(x)==1) return(x)
  mp <- regexpr('/[^\\/]+$',x, perl=TRUE)
  if (mp[[1]]==-1) return(paste(x, collapse=','))
  r <- sapply(regmatches(x,mp), substr, 2, nchar(x))
  r[[1]] <- x[[1]]
  return(paste(r, collapse=','))
})

## check if all regions are recognized and get their id:
rdf <- data.frame("id"=as.numeric(0), "name"=unique(smp$region))

dbGetQuery(con, "drop table reg_tmp")
dbWriteTable(con, name="reg_tmp", value=rdf, 
             append=FALSE, row.names=FALSE, temporary=T)
##TODO: in postgresql populate IDs in reg_tmp by vocabulary analysis


##strip RNum and convert it to numeric? not anymore
#smp$rnum <- substring(smp$rnum, 2, nchar(smp$rnum))
#smp$rnum <- as.numeric(smp$rnum)

## adding dataset_id from matching entries in ds:
smp$dataset_id <- ds$id[ match(smp$dataset, ds$name) ]
## adding subj_id
smp$subj_id <- subj$id[ match(smp$brnum, subj$brnum) ]

## load samples table through a temporary table
## rename rnum to "name" for the samples table
colnames(smp) [colnames(smp) == "rnum"] <- "name"

## 
## remove duplicate BrNum entries, keep only the last one in each group
dbGetQuery(con, "drop table samples_tmp")
dbWriteTable(con, name="samples_tmp", value=smp[c("name", "subj_id", "region")], 
             append=FALSE, row.names=FALSE, temporary=T)

dbGetQuery(con, "CREATE INDEX idx_stmp_n ON samples_tmp (name)")

qry <- "INSERT into samples (name, subj_id, region)
 SELECT DISTINCT t.name, t.subj_id, cast(t.region as sampleregion) from samples_tmp t where 
   NOT EXISTS( SELECT * from samples s where s.name = t.name 
                and s.subj_id = t.subj_id and text(s.region) = t.region)"

dbGetQuery(con, qry)

dbGetQuery(con, "drop table samples_tmp")
```

```{r}
## now load exp_RNASeq (metadata only first)

## rename "name" column to "s_name" for the exp_RNASeq table
colnames(smp) [colnames(smp) == "name"] <- "s_name"

samples=dbGetQuery(con,"select * from samples")

smp$dsmp <- paste(smp$s_name, smp$subj_id, smp$region, sep="~")

samples$dsmp <- paste(samples$name, samples$subj_id, samples$region, sep="~")

# create a join s_id column by fetching the samples$id values when matching dsmp
smp$s_id <- samples$id[ match(smp$dsmp, samples$dsmp) ]

dbGetQuery(con, "drop table exp_r_tmp")

qry <- "CREATE TEMPORARY TABLE exp_r_tmp ( s_id int, s_name varchar(42), flags bit(8), 
   sample_id varchar(240), dataset_id smallint, rin numeric(3,1), numreads int, 
   nummapped int, numunmapped int, mitomapped int, totalmapped int, overallmaprate real, 
   concordmaprate real, mitorate real, rrna_rate real, totalassignedgene real, bamfile text )"

dbGetQuery(con, qry)

dbWriteTable(con, name="exp_r_tmp", value=smp[c("s_id", "s_name", "sample_id", "dataset_id",
    "rin", "numreads", "nummapped", "numunmapped", "mitomapped", "totalmapped",
    "overallmaprate", "concordmaprate", "mitorate", "rrna_rate", "totalassignedgene",
    "bamfile")], append=TRUE, row.names=FALSE)

dbGetQuery(con, "CREATE INDEX idx_rnaseqtmp_sid ON exp_r_tmp (sample_id)")

qry <- "INSERT into exp_rnaseq (s_id, s_name, flags, sample_id, dataset_id, rin, 
    numreads, nummapped, numunmapped, mitomapped, totalmapped,
    overallmaprate, concordmaprate, mitorate, rrna_rate, totalassignedgene, bamfile)
     SELECT * from exp_r_tmp t where 
      NOT EXISTS( SELECT * from exp_rnaseq r where r.sample_id = t.sample_id)"

dbGetQuery(con, qry)


```

